version: "3"
services:
  mongodb:
    image: cr.yandex/crps5m51hmah43pmfb23/mongodb:4.4
    container_name: unic.chat.db.mongo
    restart: on-failure
    volumes:
      - mongodb_data:/bitnami/mongodb
    env_file:
      - mongo.env
    ports:
      - "27017:27017"
    networks:
      - unicchat-backend
      - unicchat-frontend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  unic.chat.solid:
    image: cr.yandex/crpi5ll6mqcn793fvu9i/unicchat.solid/prod:prod250421
    container_name: unic.chat.solid
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - 8881:8080
      - 4443:443
    env_file:
      - solid.env
    networks:
      - unicchat-backend

  unic.chat.appserver:
    container_name: unic.chat.appserver
    image: cr.yandex/crpvpl7g37r2id3i2qe5/unic_chat_appserver:prod.6-2.1.76-4
    restart: on-failure
    depends_on:
      unic.chat.solid:
        condition: service_started
    env_file:
      - appserver.env
    volumes:
      - chat_data:/app/uploads
    ports:
      - "8080:3000"
    networks:
      - unicchat-frontend

networks:
  unicchat-frontend:
    driver: bridge
    external: true
  unicchat-backend:
    driver: bridge
    external: true

volumes:
  mongodb_data:
    driver: local
  chat_data:
    driver: local
